from tkinter import *
r = Tk()
r.title("Pros tho botton")
r.geometry("400x400")
def handle_keypress(event):  print(event.char)
r.bind("<Key>", handle_keypress)
def handle_click(event):  print("The Button was clicked")
buttonon = Button(r, text="Click Me")
buttonon.pack()
buttonon.bind("<Button-1>", handle_click)
r.mainloop()